---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: farmdoc-postgres-pv
  labels:
    name: farmdoc-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /radiant/projects/bbdk/farmdoc-tst/datawolf
    server: radiant-nfs.ncsa.illinois.edu
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  selector:
    matchLabels:
      name: farmdoc-postgres
