apiVersion: v1
kind: PersistentVolume
metadata:
  name: farmdoc-postgres-pv
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mr/zk