apiVersion: v1
kind: Service
metadata:
  name: {{ include "farmdoc.fullname" . }}-frontend
  labels:
    {{- include "farmdoc.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "farmdoc.name" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      name: frontend
      targetPort: http
      protocol: TCP
