{{- if .Values.keycloak.realmsecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "farmdoc.fullname" . }}-realm-secret
  labels:
    {{- include "farmdoc.labels" . | nindent 4 }}
type: generic
data:
  "realm.json": {{ .Files.Get .Values.keycloak.realmsecret | b64enc | quote }}
{{- end }}
