{{- if .Values.keycloak.realmsecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "farmdoc.fullname" . }}-realm-secret
  labels:
    {{- include "farmdoc.labels" . | nindent 4 }}
type: generic
data:
  "realm.json": {{ .Files.Get .Values.keycloak.realmsecret | b64enc | quote }}
  postgres-password: {{ .Vales.postgresql.auth.postgresPassword | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "farmdoc.fullname" . }}-keycloak
  labels:
  {{- include "farmdoc.labels" . | nindent 4 }}
data:
  admin-password: {{ .Values.keycloak.auth.adminPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "farmdoc.fullname" . }}-postgresql
  labels:
  {{- include "farmdoc.labels" . | nindent 4 }}
data:
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
